---
pdf_document:
  number_sections: yes
  toc: yes
  tocdepth: 2
author: "Daria Svidzinska"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
title: "Description of Surface Metrics"
fontsize: 12pt
# it's imporatnt when you knit to make sure that you knit to project directory
# Knit -> Knit Directory -> Project Directory
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

Landscape metrics implemented in FragStats have been a rule of thumb in the analysis of landscape pattern for several reasons. First of all, it was a useful tool to quantify landscape patch and pattern structure as it was presented in all landscape ecological studies. Secondly, there is a huge set a well-defined quantitative metrics available for any task whether it is landscape diversity, complexity or simply fragmentation. And last but not least there is a specially designed and well-documented software package available for free.

But McGarigal and X (XXX) suggested that a classical view of landscape patch-and-matrix matrix is too simplified comparing to real-world continuity. They suggested that discrete models should be replaced (or at least try to be) by a gradient model. And while at first it was pretty difficult to find and represent landscape gradients, with the invention of advanced geoinformational data representation and storage capabilities, as well as billions of terabytes of remote sensing data continuously becoming available for free it became more clear that it is much easier and appropriate to use gradient model to represent and analyze landscape and its properties.

# Surface Metrics

## Amplitude Metrics

### Average Rougness (Arithmetic Average Height)

$$R_a = \frac{1}{n} \sum_{i=1}^{n} \left| \bar{y} - y_i \right|$$